// Auto-generated company logo registry from gilbarbara/logos
// 1417 companies

export const COMPANIES = [
  { slug: "100tb", name: "100TB" },
  { slug: "500px", name: "500px" },
  { slug: "active-campaign", name: "Active Campaign" },
  { slug: "adobe", name: "Adobe" },
  { slug: "adobe-after-effects", name: "Adobe After Effects" },
  { slug: "adobe-animate", name: "Adobe Animate" },
  { slug: "adobe-dreamweaver", name: "Adobe Dreamweaver" },
  { slug: "adobe-illustrator", name: "Adobe Illustrator" },
  { slug: "adobe-incopy", name: "Adobe Incopy" },
  { slug: "adobe-indesign", name: "Adobe Indesign" },
  { slug: "adobe-lightroom", name: "Adobe Lightroom" },
  { slug: "adobe-photoshop", name: "Adobe Photoshop" },
  { slug: "adobe-premiere", name: "Adobe Premiere" },
  { slug: "adobe-xd", name: "Adobe Xd" },
  { slug: "adonisjs", name: "Adonisjs" },
  { slug: "adroll", name: "Adroll" },
  { slug: "adyen", name: "Adyen" },
  { slug: "aerogear", name: "Aerogear" },
  { slug: "aerospike", name: "Aerospike" },
  { slug: "aha", name: "Aha" },
  { slug: "airbnb", name: "Airbnb" },
  { slug: "airbrake", name: "Airbrake" },
  { slug: "airflow", name: "Airflow" },
  { slug: "airtable", name: "Airtable" },
  { slug: "aix", name: "Aix" },
  { slug: "akamai", name: "Akamai" },
  { slug: "akka", name: "Akka" },
  { slug: "alfresco", name: "Alfresco" },
  { slug: "algolia", name: "Algolia" },
  { slug: "alpinejs", name: "Alpinejs" },
  { slug: "altair", name: "Altair" },
  { slug: "amazon", name: "Amazon" },
  { slug: "amazon-chime", name: "Amazon Chime" },
  { slug: "amazon-connect", name: "Amazon Connect" },
  { slug: "amd", name: "Amd" },
  { slug: "amex", name: "Amex" },
  { slug: "amex-digital", name: "Amex Digital" },
  { slug: "amp", name: "Amp" },
  { slug: "ampersand", name: "Ampersand" },
  { slug: "amplication", name: "Amplication" },
  { slug: "amplitude", name: "Amplitude" },
  { slug: "analog", name: "Analog" },
  { slug: "android", name: "Android" },
  { slug: "android-vertical", name: "Android Vertical" },
  { slug: "angellist", name: "Angellist" },
  { slug: "angular", name: "Angular" },
  { slug: "ansible", name: "Ansible" },
  { slug: "ant-design", name: "Ant Design" },
  { slug: "anthropic", name: "Anthropic" },
  { slug: "apache", name: "Apache" },
  { slug: "apache-camel", name: "Apache Camel" },
  { slug: "apache-flink", name: "Apache Flink" },
  { slug: "apache-spark", name: "Apache Spark" },
  { slug: "apache-superset", name: "Apache Superset" },
  { slug: "apache_cloudstack", name: "Apache_cloudstack" },
  { slug: "apiary", name: "Apiary" },
  { slug: "apidog", name: "Apidog" },
  { slug: "apollostack", name: "Apollostack" },
  { slug: "apostrophe", name: "Apostrophe" },
  { slug: "appbaseio", name: "Appbaseio" },
  { slug: "appcenter", name: "Appcenter" },
  { slug: "appcircle", name: "Appcircle" },
  { slug: "appcode", name: "Appcode" },
  { slug: "appdynamics", name: "Appdynamics" },
  { slug: "appium", name: "Appium" },
  { slug: "apple", name: "Apple" },
  { slug: "apple-app-store", name: "Apple App Store" },
  { slug: "apple-pay", name: "Apple Pay" },
  { slug: "applitools", name: "Applitools" },
  { slug: "appsignal", name: "Appsignal" },
  { slug: "apptentive", name: "Apptentive" },
  { slug: "appveyor", name: "Appveyor" },
  { slug: "appwrite", name: "Appwrite" },
  { slug: "arangodb", name: "Arangodb" },
  { slug: "arc", name: "Arc" },
  { slug: "architect", name: "Architect" },
  { slug: "archlinux", name: "Archlinux" },
  { slug: "arduino", name: "Arduino" },
  { slug: "argo", name: "Argo" },
  { slug: "arm", name: "Arm" },
  { slug: "armory", name: "Armory" },
  { slug: "asana", name: "Asana" },
  { slug: "asciidoctor", name: "Asciidoctor" },
  { slug: "assembla", name: "Assembla" },
  { slug: "astro", name: "Astro" },
  { slug: "astronomer", name: "Astronomer" },
  { slug: "async-api", name: "Async Api" },
  { slug: "atlassian", name: "Atlassian" },
  { slug: "atom", name: "Atom" },
  { slug: "atomic", name: "Atomic" },
  { slug: "atomicojs", name: "Atomicojs" },
  { slug: "aurelia", name: "Aurelia" },
  { slug: "aurora", name: "Aurora" },
  { slug: "auth0", name: "Auth0" },
  { slug: "authy", name: "Authy" },
  { slug: "autoit", name: "Autoit" },
  { slug: "autoprefixer", name: "Autoprefixer" },
  { slug: "ava", name: "Ava" },
  { slug: "awesome", name: "Awesome" },
  { slug: "aws", name: "AWS" },
  { slug: "aws-amplify", name: "Aws Amplify" },
  { slug: "aws-api-gateway", name: "Aws Api Gateway" },
  { slug: "aws-app-mesh", name: "Aws App Mesh" },
  { slug: "aws-appflow", name: "Aws Appflow" },
  { slug: "aws-appsync", name: "Aws Appsync" },
  { slug: "aws-athena", name: "Aws Athena" },
  { slug: "aws-aurora", name: "Aws Aurora" },
  { slug: "aws-backup", name: "Aws Backup" },
  { slug: "aws-batch", name: "Aws Batch" },
  { slug: "aws-certificate-manager", name: "Aws Certificate Manager" },
  { slug: "aws-cloudformation", name: "Aws Cloudformation" },
  { slug: "aws-cloudfront", name: "Aws Cloudfront" },
  { slug: "aws-cloudsearch", name: "Aws Cloudsearch" },
  { slug: "aws-cloudtrail", name: "Aws Cloudtrail" },
  { slug: "aws-cloudwatch", name: "Aws Cloudwatch" },
  { slug: "aws-codebuild", name: "Aws Codebuild" },
  { slug: "aws-codecommit", name: "Aws Codecommit" },
  { slug: "aws-codedeploy", name: "Aws Codedeploy" },
  { slug: "aws-codepipeline", name: "Aws Codepipeline" },
  { slug: "aws-codestar", name: "Aws Codestar" },
  { slug: "aws-cognito", name: "Aws Cognito" },
  { slug: "aws-config", name: "Aws Config" },
  { slug: "aws-documentdb", name: "Aws Documentdb" },
  { slug: "aws-dynamodb", name: "Aws Dynamodb" },
  { slug: "aws-ec2", name: "Aws Ec2" },
  { slug: "aws-ecs", name: "Aws Ecs" },
  { slug: "aws-eks", name: "Aws Eks" },
  { slug: "aws-elastic-beanstalk", name: "Aws Elastic Beanstalk" },
  { slug: "aws-elasticache", name: "Aws Elasticache" },
  { slug: "aws-elb", name: "Aws Elb" },
  { slug: "aws-eventbridge", name: "Aws Eventbridge" },
  { slug: "aws-fargate", name: "Aws Fargate" },
  { slug: "aws-glacier", name: "Aws Glacier" },
  { slug: "aws-glue", name: "Aws Glue" },
  { slug: "aws-iam", name: "Aws Iam" },
  { slug: "aws-keyspaces", name: "Aws Keyspaces" },
  { slug: "aws-kinesis", name: "Aws Kinesis" },
  { slug: "aws-kms", name: "Aws Kms" },
  { slug: "aws-lake-formation", name: "Aws Lake Formation" },
  { slug: "aws-lambda", name: "Aws Lambda" },
  { slug: "aws-lightsail", name: "Aws Lightsail" },
  { slug: "aws-mq", name: "Aws Mq" },
  { slug: "aws-msk", name: "Aws Msk" },
  { slug: "aws-neptune", name: "Aws Neptune" },
  { slug: "aws-open-search", name: "Aws Open Search" },
  { slug: "aws-opsworks", name: "Aws Opsworks" },
  { slug: "aws-quicksight", name: "Aws Quicksight" },
  { slug: "aws-rds", name: "Aws Rds" },
  { slug: "aws-redshift", name: "Aws Redshift" },
  { slug: "aws-route53", name: "Aws Route53" },
  { slug: "aws-s3", name: "Aws S3" },
  { slug: "aws-secrets-manager", name: "Aws Secrets Manager" },
  { slug: "aws-ses", name: "Aws Ses" },
  { slug: "aws-shield", name: "Aws Shield" },
  { slug: "aws-sns", name: "Aws Sns" },
  { slug: "aws-sqs", name: "Aws Sqs" },
  { slug: "aws-step-functions", name: "Aws Step Functions" },
  { slug: "aws-systems-manager", name: "Aws Systems Manager" },
  { slug: "aws-timestream", name: "Aws Timestream" },
  { slug: "aws-vpc", name: "Aws Vpc" },
  { slug: "aws-waf", name: "Aws Waf" },
  { slug: "aws-xray", name: "Aws Xray" },
  { slug: "axios", name: "Axios" },
  { slug: "babel", name: "Babel" },
  { slug: "backbone", name: "Backbone" },
  { slug: "backerkit", name: "Backerkit" },
  { slug: "baker-street", name: "Baker Street" },
  { slug: "balena", name: "Balena" },
  { slug: "bamboo", name: "Bamboo" },
  { slug: "basecamp", name: "Basecamp" },
  { slug: "basekit", name: "Basekit" },
  { slug: "baseline", name: "Baseline" },
  { slug: "bash", name: "Bash" },
  { slug: "batch", name: "Batch" },
  { slug: "beats", name: "Beats" },
  { slug: "behance", name: "Behance" },
  { slug: "bem", name: "Bem" },
  { slug: "bem-2", name: "Bem 2" },
  { slug: "bigpanda", name: "Bigpanda" },
  { slug: "bing", name: "Bing" },
  { slug: "biomejs", name: "Biomejs" },
  { slug: "bitbar", name: "Bitbar" },
  { slug: "bitbucket", name: "Bitbucket" },
  { slug: "bitcoin", name: "Bitcoin" },
  { slug: "bitnami", name: "Bitnami" },
  { slug: "bitrise", name: "Bitrise" },
  { slug: "blender", name: "Blender" },
  { slug: "blitzjs", name: "Blitzjs" },
  { slug: "blocs", name: "Blocs" },
  { slug: "blogger", name: "Blogger" },
  { slug: "blossom", name: "Blossom" },
  { slug: "blueprint", name: "Blueprint" },
  { slug: "bluesky", name: "Bluesky" },
  { slug: "bluetooth", name: "Bluetooth" },
  { slug: "booqable", name: "Booqable" },
  { slug: "bootstrap", name: "Bootstrap" },
  { slug: "bosun", name: "Bosun" },
  { slug: "botanalytics", name: "Botanalytics" },
  { slug: "bourbon", name: "Bourbon" },
  { slug: "bower", name: "Bower" },
  { slug: "box", name: "Box" },
  { slug: "brackets", name: "Brackets" },
  { slug: "brainjs", name: "Brainjs" },
  { slug: "branch", name: "Branch" },
  { slug: "brandfolder", name: "Brandfolder" },
  { slug: "brave", name: "Brave" },
  { slug: "braze", name: "Braze" },
  { slug: "broadcom", name: "Broadcom" },
  { slug: "broccoli", name: "Broccoli" },
  { slug: "brotli", name: "Brotli" },
  { slug: "browserify", name: "Browserify" },
  { slug: "browserling", name: "Browserling" },
  { slug: "browserslist", name: "Browserslist" },
  { slug: "browserstack", name: "Browserstack" },
  { slug: "browsersync", name: "Browsersync" },
  { slug: "brunch", name: "Brunch" },
  { slug: "bubble", name: "Bubble" },
  { slug: "buck", name: "Buck" },
  { slug: "buddy", name: "Buddy" },
  { slug: "buffer", name: "Buffer" },
  { slug: "bugherd", name: "Bugherd" },
  { slug: "bugsee", name: "Bugsee" },
  { slug: "bugsnag", name: "Bugsnag" },
  { slug: "builder-io", name: "Builder Io" },
  { slug: "buildkite", name: "Buildkite" },
  { slug: "bulma", name: "Bulma" },
  { slug: "bun", name: "Bun" },
  { slug: "bunny-net", name: "Bunny Net" },
  { slug: "c", name: "C" },
  { slug: "c-plusplus", name: "C Plusplus" },
  { slug: "c-sharp", name: "C Sharp" },
  { slug: "cachet", name: "Cachet" },
  { slug: "cakephp", name: "Cakephp" },
  { slug: "calibre", name: "Calibre" },
  { slug: "campaignmonitor", name: "Campaignmonitor" },
  { slug: "canjs", name: "Canjs" },
  { slug: "capacitorjs", name: "Capacitorjs" },
  { slug: "capistrano", name: "Capistrano" },
  { slug: "carbide", name: "Carbide" },
  { slug: "cardano", name: "Cardano" },
  { slug: "cassandra", name: "Cassandra" },
  { slug: "centos", name: "Centos" },
  { slug: "certbot", name: "Certbot" },
  { slug: "ceylon", name: "Ceylon" },
  { slug: "chai", name: "Chai" },
  { slug: "chalk", name: "Chalk" },
  { slug: "chargebee", name: "Chargebee" },
  { slug: "chartjs", name: "Chartjs" },
  { slug: "chef", name: "Chef" },
  { slug: "chevereto", name: "Chevereto" },
  { slug: "chroma", name: "Chroma" },
  { slug: "chromatic", name: "Chromatic" },
  { slug: "chrome", name: "Chrome" },
  { slug: "chrome-web-store", name: "Chrome Web Store" },
  { slug: "cinder", name: "Cinder" },
  { slug: "circleci", name: "Circleci" },
  { slug: "cirrus", name: "Cirrus" },
  { slug: "cirrus-ci", name: "Cirrus Ci" },
  { slug: "claude", name: "Claude" },
  { slug: "clio-lang", name: "Clio Lang" },
  { slug: "clion", name: "Clion" },
  { slug: "cljs", name: "Cljs" },
  { slug: "clojure", name: "Clojure" },
  { slug: "close", name: "Close" },
  { slug: "cloud9", name: "Cloud9" },
  { slug: "cloudacademy", name: "Cloudacademy" },
  { slug: "cloudcraft", name: "Cloudcraft" },
  { slug: "cloudflare", name: "Cloudflare" },
  { slug: "cloudflare-workers", name: "Cloudflare Workers" },
  { slug: "cloudinary", name: "Cloudinary" },
  { slug: "cloudlinux", name: "Cloudlinux" },
  { slug: "cobalt", name: "Cobalt" },
  { slug: "cockpit", name: "Cockpit" },
  { slug: "cocoapods", name: "Cocoapods" },
  { slug: "coda", name: "Coda" },
  { slug: "codacy", name: "Codacy" },
  { slug: "codebase", name: "Codebase" },
  { slug: "codebeat", name: "Codebeat" },
  { slug: "codecademy", name: "Codecademy" },
  { slug: "codeception", name: "Codeception" },
  { slug: "codeclimate", name: "Codeclimate" },
  { slug: "codecov", name: "Codecov" },
  { slug: "codefactor", name: "Codefactor" },
  { slug: "codeigniter", name: "Codeigniter" },
  { slug: "codepen", name: "Codepen" },
  { slug: "codersrank", name: "Codersrank" },
  { slug: "coderwall", name: "Coderwall" },
  { slug: "codesandbox", name: "Codesandbox" },
  { slug: "codesee", name: "Codesee" },
  { slug: "codio", name: "Codio" },
  { slug: "codium", name: "Codium" },
  { slug: "coffeescript", name: "Coffeescript" },
  { slug: "commitizen", name: "Commitizen" },
  { slug: "compass", name: "Compass" },
  { slug: "componentkit", name: "Componentkit" },
  { slug: "compose", name: "Compose" },
  { slug: "compose-multiplatform", name: "Compose Multiplatform" },
  { slug: "composer", name: "Composer" },
  { slug: "conan-io", name: "Conan Io" },
  { slug: "concourse", name: "Concourse" },
  { slug: "concretecms", name: "Concretecms" },
  { slug: "conda", name: "Conda" },
  { slug: "confluence", name: "Confluence" },
  { slug: "consul", name: "Consul" },
  { slug: "contentful", name: "Contentful" },
  { slug: "convox", name: "Convox" },
  { slug: "copyleft", name: "Copyleft" },
  { slug: "copyleft-pirate", name: "Copyleft Pirate" },
  { slug: "corda", name: "Corda" },
  { slug: "cordova", name: "Cordova" },
  { slug: "couchbase", name: "Couchbase" },
  { slug: "couchdb", name: "Couchdb" },
  { slug: "coursera", name: "Coursera" },
  { slug: "coveralls", name: "Coveralls" },
  { slug: "cpanel", name: "Cpanel" },
  { slug: "craftcms", name: "Craftcms" },
  { slug: "crashlytics", name: "Crashlytics" },
  { slug: "crateio", name: "Crateio" },
  { slug: "create-react-app", name: "Create React App" },
  { slug: "createjs", name: "Createjs" },
  { slug: "crossplane", name: "Crossplane" },
  { slug: "crucible", name: "Crucible" },
  { slug: "crystal", name: "Crystal" },
  { slug: "css-3", name: "CSS3" },
  { slug: "css-3_official", name: "Css 3_official" },
  { slug: "cssnext", name: "Cssnext" },
  { slug: "cube", name: "Cube" },
  { slug: "cucumber", name: "Cucumber" },
  { slug: "curl", name: "Curl" },
  { slug: "customerio", name: "Customerio" },
  { slug: "cyclejs", name: "Cyclejs" },
  { slug: "cypress", name: "Cypress" },
  { slug: "d3", name: "D3" },
  { slug: "dailydev", name: "Dailydev" },
  { slug: "daisyUI", name: "Daisyui" },
  { slug: "danfo", name: "Danfo" },
  { slug: "dart", name: "Dart" },
  { slug: "dashlane", name: "Dashlane" },
  { slug: "data-station", name: "Data Station" },
  { slug: "database-labs", name: "Database Labs" },
  { slug: "datadog", name: "Datadog" },
  { slug: "datagrip", name: "Datagrip" },
  { slug: "datasette", name: "Datasette" },
  { slug: "dataspell", name: "Dataspell" },
  { slug: "datocms", name: "Datocms" },
  { slug: "dbt", name: "Dbt" },
  { slug: "dcos", name: "Dcos" },
  { slug: "debian", name: "Debian" },
  { slug: "delighted", name: "Delighted" },
  { slug: "deno", name: "Deno" },
  { slug: "dependabot", name: "Dependabot" },
  { slug: "deployhq", name: "Deployhq" },
  { slug: "derby", name: "Derby" },
  { slug: "descript", name: "Descript" },
  { slug: "designernews", name: "Designernews" },
  { slug: "deviantart", name: "Deviantart" },
  { slug: "dgraph", name: "Dgraph" },
  { slug: "dialogflow", name: "Dialogflow" },
  { slug: "digital-ocean", name: "Digital Ocean" },
  { slug: "dimer", name: "Dimer" },
  { slug: "dinersclub", name: "Dinersclub" },
  { slug: "discord", name: "Discord" },
  { slug: "discourse", name: "Discourse" },
  { slug: "discover", name: "Discover" },
  { slug: "disqus", name: "Disqus" },
  { slug: "django", name: "Django" },
  { slug: "dockbit", name: "Dockbit" },
  { slug: "docker", name: "Docker" },
  { slug: "doctrine", name: "Doctrine" },
  { slug: "docusaurus", name: "Docusaurus" },
  { slug: "dojo", name: "Dojo" },
  { slug: "dojo-toolkit", name: "Dojo Toolkit" },
  { slug: "dolt", name: "Dolt" },
  { slug: "dotnet", name: "Dotnet" },
  { slug: "dovetail", name: "Dovetail" },
  { slug: "dreamhost", name: "Dreamhost" },
  { slug: "dribbble", name: "Dribbble" },
  { slug: "drift", name: "Drift" },
  { slug: "drip", name: "Drip" },
  { slug: "drizzle", name: "Drizzle" },
  { slug: "drone", name: "Drone" },
  { slug: "drools", name: "Drools" },
  { slug: "dropbox", name: "Dropbox" },
  { slug: "dropmark", name: "Dropmark" },
  { slug: "dropzone", name: "Dropzone" },
  { slug: "drupal", name: "Drupal" },
  { slug: "duckduckgo", name: "Duckduckgo" },
  { slug: "dynatrace", name: "Dynatrace" },
  { slug: "dyndns", name: "Dyndns" },
  { slug: "ebanx", name: "Ebanx" },
  { slug: "eclipse", name: "Eclipse" },
  { slug: "ecma", name: "Ecma" },
  { slug: "edgedb", name: "Edgedb" },
  { slug: "edgio", name: "Edgio" },
  { slug: "editorconfig", name: "Editorconfig" },
  { slug: "effect", name: "Effect" },
  { slug: "effector", name: "Effector" },
  { slug: "egghead", name: "Egghead" },
  { slug: "elastic", name: "Elastic" },
  { slug: "elasticpath", name: "Elasticpath" },
  { slug: "elasticsearch", name: "Elasticsearch" },
  { slug: "electron", name: "Electron" },
  { slug: "element", name: "Element" },
  { slug: "elemental-ui", name: "Elemental Ui" },
  { slug: "elementary", name: "Elementary" },
  { slug: "eleventy", name: "Eleventy" },
  { slug: "ello", name: "Ello" },
  { slug: "elm", name: "Elm" },
  { slug: "elm-classic", name: "Elm Classic" },
  { slug: "elo", name: "Elo" },
  { slug: "emacs", name: "Emacs" },
  { slug: "emacs-classic", name: "Emacs Classic" },
  { slug: "embedly", name: "Embedly" },
  { slug: "ember", name: "Ember" },
  { slug: "ember-tomster", name: "Ember Tomster" },
  { slug: "emmet", name: "Emmet" },
  { slug: "enact", name: "Enact" },
  { slug: "engine-yard", name: "Engine Yard" },
  { slug: "envato", name: "Envato" },
  { slug: "envoy", name: "Envoy" },
  { slug: "envoyer", name: "Envoyer" },
  { slug: "eraser", name: "Eraser" },
  { slug: "erlang", name: "Erlang" },
  { slug: "esbuild", name: "Esbuild" },
  { slug: "esdoc", name: "Esdoc" },
  { slug: "eslint", name: "Eslint" },
  { slug: "eslint-old", name: "Eslint Old" },
  { slug: "eta", name: "Eta" },
  { slug: "etcd", name: "Etcd" },
  { slug: "ethereum", name: "Ethereum" },
  { slug: "ethereum-color", name: "Ethereum Color" },
  { slug: "ethers", name: "Ethers" },
  { slug: "ethnio", name: "Ethnio" },
  { slug: "eventbrite", name: "Eventbrite" },
  { slug: "eventsentry", name: "Eventsentry" },
  { slug: "evergreen", name: "Evergreen" },
  { slug: "expo", name: "Expo" },
  { slug: "express", name: "Express" },
  { slug: "fabric", name: "Fabric" },
  { slug: "facebook", name: "Facebook" },
  { slug: "faker", name: "Faker" },
  { slug: "falcor", name: "Falcor" },
  { slug: "fastapi", name: "Fastapi" },
  { slug: "fastify", name: "Fastify" },
  { slug: "fastlane", name: "Fastlane" },
  { slug: "fastly", name: "Fastly" },
  { slug: "fauna", name: "Fauna" },
  { slug: "feathersjs", name: "Feathersjs" },
  { slug: "fedora", name: "Fedora" },
  { slug: "fetch", name: "Fetch" },
  { slug: "ffmpeg", name: "Ffmpeg" },
  { slug: "figma", name: "Figma" },
  { slug: "firebase", name: "Firebase" },
  { slug: "firefox", name: "Firefox" },
  { slug: "flannel", name: "Flannel" },
  { slug: "flarum", name: "Flarum" },
  { slug: "flask", name: "Flask" },
  { slug: "flat-ui", name: "Flat Ui" },
  { slug: "flattr", name: "Flattr" },
  { slug: "fleep", name: "Fleep" },
  { slug: "flickr", name: "Flickr" },
  { slug: "flight", name: "Flight" },
  { slug: "floodio", name: "Floodio" },
  { slug: "flow", name: "Flow" },
  { slug: "flowxo", name: "Flowxo" },
  { slug: "floydhub", name: "Floydhub" },
  { slug: "flutter", name: "Flutter" },
  { slug: "flux", name: "Flux" },
  { slug: "fluxxor", name: "Fluxxor" },
  { slug: "fly", name: "Fly" },
  { slug: "fogbugz", name: "Fogbugz" },
  { slug: "fomo", name: "Fomo" },
  { slug: "font-awesome", name: "Font Awesome" },
  { slug: "forestadmin", name: "Forestadmin" },
  { slug: "forever", name: "Forever" },
  { slug: "formkeep", name: "Formkeep" },
  { slug: "fortran", name: "Fortran" },
  { slug: "foundation", name: "Foundation" },
  { slug: "foundationdb", name: "Foundationdb" },
  { slug: "framer", name: "Framer" },
  { slug: "framework7", name: "Framework7" },
  { slug: "freebsd", name: "Freebsd" },
  { slug: "freedcamp", name: "Freedcamp" },
  { slug: "freedomdefined", name: "Freedomdefined" },
  { slug: "fresh", name: "Fresh" },
  { slug: "frontapp", name: "Frontapp" },
  { slug: "fsharp", name: "Fsharp" },
  { slug: "fuchsia", name: "Fuchsia" },
  { slug: "galliumos", name: "Galliumos" },
  { slug: "game-analytics", name: "Game Analytics" },
  { slug: "ganache", name: "Ganache" },
  { slug: "gatsby", name: "Gatsby" },
  { slug: "geekbot", name: "Geekbot" },
  { slug: "geetest", name: "Geetest" },
  { slug: "getyourguide", name: "Getyourguide" },
  { slug: "ghost", name: "Ghost" },
  { slug: "giantswarm", name: "Giantswarm" },
  { slug: "gin", name: "Gin" },
  { slug: "git", name: "Git" },
  { slug: "gitboard", name: "Gitboard" },
  { slug: "github", name: "GitHub" },
  { slug: "github-actions", name: "Github Actions" },
  { slug: "github-copilot", name: "Github Copilot" },
  { slug: "github-octocat", name: "Github Octocat" },
  { slug: "gitkraken", name: "Gitkraken" },
  { slug: "gitlab", name: "GitLab" },
  { slug: "gitter", name: "Gitter" },
  { slug: "gitup", name: "Gitup" },
  { slug: "glamorous", name: "Glamorous" },
  { slug: "gleam", name: "Gleam" },
  { slug: "glimmerjs", name: "Glimmerjs" },
  { slug: "glint", name: "Glint" },
  { slug: "glitch", name: "Glitch" },
  { slug: "gnome", name: "Gnome" },
  { slug: "gnu", name: "Gnu" },
  { slug: "gnu-net", name: "Gnu Net" },
  { slug: "gnupg", name: "Gnupg" },
  { slug: "go", name: "Go" },
  { slug: "gocd", name: "Gocd" },
  { slug: "godot", name: "Godot" },
  { slug: "gohorse", name: "Gohorse" },
  { slug: "goland", name: "Goland" },
  { slug: "google", name: "Google" },
  { slug: "google-360suite", name: "Google 360suite" },
  { slug: "google-admob", name: "Google Admob" },
  { slug: "google-ads", name: "Google Ads" },
  { slug: "google-adsense", name: "Google Adsense" },
  { slug: "google-analytics", name: "Google Analytics" },
  { slug: "google-bard", name: "Google Bard" },
  { slug: "google-calendar", name: "Google Calendar" },
  { slug: "google-cloud", name: "Google Cloud" },
  { slug: "google-cloud-functions", name: "Google Cloud Functions" },
  { slug: "google-cloud-run", name: "Google Cloud Run" },
  { slug: "google-data-studio", name: "Google Data Studio" },
  { slug: "google-developers", name: "Google Developers" },
  { slug: "google-domains", name: "Google Domains" },
  { slug: "google-drive", name: "Google Drive" },
  { slug: "google-fit", name: "Google Fit" },
  { slug: "google-gemini", name: "Google Gemini" },
  { slug: "google-gmail", name: "Google Gmail" },
  { slug: "google-home", name: "Google Home" },
  { slug: "google-keep", name: "Google Keep" },
  { slug: "google-maps", name: "Google Maps" },
  { slug: "google-marketing-platform", name: "Google Marketing Platform" },
  { slug: "google-meet", name: "Google Meet" },
  { slug: "google-one", name: "Google One" },
  { slug: "google-optimize", name: "Google Optimize" },
  { slug: "google-palm", name: "Google Palm" },
  { slug: "google-pay", name: "Google Pay" },
  { slug: "google-photos", name: "Google Photos" },
  { slug: "google-play", name: "Google Play" },
  { slug: "google-play-console", name: "Google Play Console" },
  { slug: "google-search-console", name: "Google Search Console" },
  { slug: "google-tag-manager", name: "Google Tag Manager" },
  { slug: "google-workspace", name: "Google Workspace" },
  { slug: "gopher", name: "Gopher" },
  { slug: "gradio", name: "Gradio" },
  { slug: "gradle", name: "Gradle" },
  { slug: "grafana", name: "Grafana" },
  { slug: "grails", name: "Grails" },
  { slug: "grammarly", name: "Grammarly" },
  { slug: "graphene", name: "Graphene" },
  { slug: "graphql", name: "GraphQL" },
  { slug: "grav", name: "Grav" },
  { slug: "gravatar", name: "Gravatar" },
  { slug: "graylog", name: "Graylog" },
  { slug: "greensock", name: "Greensock" },
  { slug: "gridsome", name: "Gridsome" },
  { slug: "grommet", name: "Grommet" },
  { slug: "groovehq", name: "Groovehq" },
  { slug: "grove", name: "Grove" },
  { slug: "growth-book", name: "Growth Book" },
  { slug: "grpc", name: "Grpc" },
  { slug: "grunt", name: "Grunt" },
  { slug: "gulp", name: "Gulp" },
  { slug: "gunicorn", name: "Gunicorn" },
  { slug: "gunjs", name: "Gunjs" },
  { slug: "gusto", name: "Gusto" },
  { slug: "gwt", name: "Gwt" },
  { slug: "hack", name: "Hack" },
  { slug: "hacker-one", name: "Hacker One" },
  { slug: "hadoop", name: "Hadoop" },
  { slug: "haiku", name: "Haiku" },
  { slug: "haml", name: "Haml" },
  { slug: "hanami", name: "Hanami" },
  { slug: "handlebars", name: "Handlebars" },
  { slug: "hapi", name: "Hapi" },
  { slug: "hardhat", name: "Hardhat" },
  { slug: "harness", name: "Harness" },
  { slug: "hashicorp", name: "Hashicorp" },
  { slug: "hashnode", name: "Hashnode" },
  { slug: "haskell", name: "Haskell" },
  { slug: "hasura", name: "Hasura" },
  { slug: "haxe", name: "Haxe" },
  { slug: "haxl", name: "Haxl" },
  { slug: "hbase", name: "Hbase" },
  { slug: "hcaptcha", name: "Hcaptcha" },
  { slug: "headlessui", name: "Headlessui" },
  { slug: "heap", name: "Heap" },
  { slug: "helm", name: "Helm" },
  { slug: "helpscout", name: "Helpscout" },
  { slug: "hermes", name: "Hermes" },
  { slug: "heroku", name: "Heroku" },
  { slug: "heroku-redis", name: "Heroku Redis" },
  { slug: "hexo", name: "Hexo" },
  { slug: "hhvm", name: "Hhvm" },
  { slug: "hibernate", name: "Hibernate" },
  { slug: "highcharts", name: "Highcharts" },
  { slug: "hipercard", name: "Hipercard" },
  { slug: "homebrew", name: "Homebrew" },
  { slug: "hono", name: "Hono" },
  { slug: "hookstate", name: "Hookstate" },
  { slug: "hootsuite", name: "Hootsuite" },
  { slug: "hosted-graphite", name: "Hosted Graphite" },
  { slug: "hostgator", name: "Hostgator" },
  { slug: "hotjar", name: "Hotjar" },
  { slug: "houndci", name: "Houndci" },
  { slug: "html-5", name: "HTML5" },
  { slug: "html5-boilerplate", name: "Html5 Boilerplate" },
  { slug: "htmx", name: "Htmx" },
  { slug: "httpie", name: "Httpie" },
  { slug: "hubspot", name: "Hubspot" },
  { slug: "hugging-face", name: "Hugging Face" },
  { slug: "huggy", name: "Huggy" },
  { slug: "hugo", name: "Hugo" },
  { slug: "humongous", name: "Humongous" },
  { slug: "hyper", name: "Hyper" },
  { slug: "hyperapp", name: "Hyperapp" },
  { slug: "ibm", name: "IBM" },
  { slug: "ieee", name: "Ieee" },
  { slug: "ietf", name: "Ietf" },
  { slug: "ifttt", name: "Ifttt" },
  { slug: "imagemin", name: "Imagemin" },
  { slug: "imba", name: "Imba" },
  { slug: "immer", name: "Immer" },
  { slug: "immutable", name: "Immutable" },
  { slug: "impala", name: "Impala" },
  { slug: "importio", name: "Importio" },
  { slug: "incident", name: "Incident" },
  { slug: "infer", name: "Infer" },
  { slug: "inferno", name: "Inferno" },
  { slug: "influxdb", name: "Influxdb" },
  { slug: "ink", name: "Ink" },
  { slug: "insomnia", name: "Insomnia" },
  { slug: "instagram", name: "Instagram" },
  { slug: "intel", name: "Intel" },
  { slug: "intellij-idea", name: "Intellij Idea" },
  { slug: "intercom", name: "Intercom" },
  { slug: "internet-computer", name: "Internet Computer" },
  { slug: "internetexplorer", name: "Internetexplorer" },
  { slug: "invision", name: "Invision" },
  { slug: "ionic", name: "Ionic" },
  { slug: "ios", name: "Ios" },
  { slug: "iron", name: "Iron" },
  { slug: "itsalive", name: "Itsalive" },
  { slug: "jade", name: "Jade" },
  { slug: "jamstack", name: "Jamstack" },
  { slug: "jasmine", name: "Jasmine" },
  { slug: "java", name: "Java" },
  { slug: "javascript", name: "JavaScript" },
  { slug: "jcb", name: "Jcb" },
  { slug: "jekyll", name: "Jekyll" },
  { slug: "jenkins", name: "Jenkins" },
  { slug: "jest", name: "Jest" },
  { slug: "jetbrains", name: "Jetbrains" },
  { slug: "jetbrains-space", name: "Jetbrains Space" },
  { slug: "jfrog", name: "Jfrog" },
  { slug: "jhipster", name: "Jhipster" },
  { slug: "jira", name: "Jira" },
  { slug: "joomla", name: "Joomla" },
  { slug: "jotai", name: "Jotai" },
  { slug: "jquery", name: "Jquery" },
  { slug: "jquery-mobile", name: "Jquery Mobile" },
  { slug: "jruby", name: "Jruby" },
  { slug: "jsbin", name: "Jsbin" },
  { slug: "jsdelivr", name: "Jsdelivr" },
  { slug: "jsdom", name: "Jsdom" },
  { slug: "jsfiddle", name: "Jsfiddle" },
  { slug: "json", name: "Json" },
  { slug: "json-ld", name: "Json Ld" },
  { slug: "json-schema", name: "Json Schema" },
  { slug: "jspm", name: "Jspm" },
  { slug: "jss", name: "Jss" },
  { slug: "juju", name: "Juju" },
  { slug: "julia", name: "Julia" },
  { slug: "jupyter", name: "Jupyter" },
  { slug: "jwt", name: "Jwt" },
  { slug: "kafka", name: "Kafka" },
  { slug: "kaios", name: "Kaios" },
  { slug: "kallithea", name: "Kallithea" },
  { slug: "karma", name: "Karma" },
  { slug: "katalon", name: "Katalon" },
  { slug: "kde", name: "Kde" },
  { slug: "keen", name: "Keen" },
  { slug: "kemal", name: "Kemal" },
  { slug: "keycdn", name: "Keycdn" },
  { slug: "keydb", name: "Keydb" },
  { slug: "keystonejs", name: "Keystonejs" },
  { slug: "khan_academy", name: "Khan_academy" },
  { slug: "kibana", name: "Kibana" },
  { slug: "kickstarter", name: "Kickstarter" },
  { slug: "kinto", name: "Kinto" },
  { slug: "kirby", name: "Kirby" },
  { slug: "knex", name: "Knex" },
  { slug: "knockout", name: "Knockout" },
  { slug: "koa", name: "Koa" },
  { slug: "kong", name: "Kong" },
  { slug: "kops", name: "Kops" },
  { slug: "koreio", name: "Koreio" },
  { slug: "kotlin", name: "Kotlin" },
  { slug: "kraken", name: "Kraken" },
  { slug: "krakenjs", name: "Krakenjs" },
  { slug: "ktor", name: "Ktor" },
  { slug: "kubernetes", name: "Kubernetes" },
  { slug: "kustomer", name: "Kustomer" },
  { slug: "languagetool", name: "Languagetool" },
  { slug: "laravel", name: "Laravel" },
  { slug: "lastfm", name: "Lastfm" },
  { slug: "lateral", name: "Lateral" },
  { slug: "launchdarkly", name: "Launchdarkly" },
  { slug: "launchrock", name: "Launchrock" },
  { slug: "leaflet", name: "Leaflet" },
  { slug: "leankit", name: "Leankit" },
  { slug: "lerna", name: "Lerna" },
  { slug: "less", name: "Less" },
  { slug: "lets-cloud", name: "Lets Cloud" },
  { slug: "letsencrypt", name: "Letsencrypt" },
  { slug: "leveldb", name: "Leveldb" },
  { slug: "lexical", name: "Lexical" },
  { slug: "liftweb", name: "Liftweb" },
  { slug: "lighthouse", name: "Lighthouse" },
  { slug: "lightstep", name: "Lightstep" },
  { slug: "lighttpd", name: "Lighttpd" },
  { slug: "linear", name: "Linear" },
  { slug: "linkedin", name: "LinkedIn" },
  { slug: "linkerd", name: "Linkerd" },
  { slug: "linode", name: "Linode" },
  { slug: "linux-mint", name: "Linux Mint" },
  { slug: "linux-tux", name: "Linux Tux" },
  { slug: "lit", name: "Lit" },
  { slug: "litmus", name: "Litmus" },
  { slug: "loader", name: "Loader" },
  { slug: "lodash", name: "Lodash" },
  { slug: "logentries", name: "Logentries" },
  { slug: "logstash", name: "Logstash" },
  { slug: "lookback", name: "Lookback" },
  { slug: "looker", name: "Looker" },
  { slug: "loom", name: "Loom" },
  { slug: "loopback", name: "Loopback" },
  { slug: "losant", name: "Losant" },
  { slug: "lua", name: "Lua" },
  { slug: "lucene", name: "Lucene" },
  { slug: "lucene.net", name: "Lucene.net" },
  { slug: "lumen", name: "Lumen" },
  { slug: "macOS", name: "Macos" },
  { slug: "madge", name: "Madge" },
  { slug: "maestro", name: "Maestro" },
  { slug: "mageia", name: "Mageia" },
  { slug: "mailchimp", name: "Mailchimp" },
  { slug: "mailchimp-freddie", name: "Mailchimp Freddie" },
  { slug: "maildeveloper", name: "Maildeveloper" },
  { slug: "mailgun", name: "Mailgun" },
  { slug: "mailjet", name: "Mailjet" },
  { slug: "malinajs", name: "Malinajs" },
  { slug: "manjaro", name: "Manjaro" },
  { slug: "mantine", name: "Mantine" },
  { slug: "mapbox", name: "Mapbox" },
  { slug: "maps-me", name: "Maps Me" },
  { slug: "mapzen", name: "Mapzen" },
  { slug: "mariadb", name: "Mariadb" },
  { slug: "marionette", name: "Marionette" },
  { slug: "markdown", name: "Markdown" },
  { slug: "marko", name: "Marko" },
  { slug: "marvel", name: "Marvel" },
  { slug: "mastercard", name: "Mastercard" },
  { slug: "mastodon", name: "Mastodon" },
  { slug: "material-ui", name: "Material Ui" },
  { slug: "materializecss", name: "Materializecss" },
  { slug: "matomo", name: "Matomo" },
  { slug: "matplotlib", name: "Matplotlib" },
  { slug: "matter", name: "Matter" },
  { slug: "mattermost", name: "Mattermost" },
  { slug: "mautic", name: "Mautic" },
  { slug: "maven", name: "Maven" },
  { slug: "mdn", name: "Mdn" },
  { slug: "mdx", name: "Mdx" },
  { slug: "medium", name: "Medium" },
  { slug: "medusa", name: "Medusa" },
  { slug: "meilisearch", name: "Meilisearch" },
  { slug: "memcached", name: "Memcached" },
  { slug: "memgraph", name: "Memgraph" },
  { slug: "mention", name: "Mention" },
  { slug: "mercurial", name: "Mercurial" },
  { slug: "mesos", name: "Mesos" },
  { slug: "messenger", name: "Messenger" },
  { slug: "meta", name: "Meta" },
  { slug: "metabase", name: "Metabase" },
  { slug: "metamask", name: "Metamask" },
  { slug: "meteor", name: "Meteor" },
  { slug: "micro", name: "Micro" },
  { slug: "micro-python", name: "Micro Python" },
  { slug: "microcosm", name: "Microcosm" },
  { slug: "micron", name: "Micron" },
  { slug: "microsoft", name: "Microsoft" },
  { slug: "microsoft-azure", name: "Microsoft Azure" },
  { slug: "microsoft-edge", name: "Microsoft Edge" },
  { slug: "microsoft-onedrive", name: "Microsoft Onedrive" },
  { slug: "microsoft-power-bi", name: "Microsoft Power Bi" },
  { slug: "microsoft-teams", name: "Microsoft Teams" },
  { slug: "microsoft-windows", name: "Microsoft Windows" },
  { slug: "mida", name: "Mida" },
  { slug: "middleman", name: "Middleman" },
  { slug: "midjourney", name: "Midjourney" },
  { slug: "milligram", name: "Milligram" },
  { slug: "million", name: "Million" },
  { slug: "milvus", name: "Milvus" },
  { slug: "mindsdb", name: "Mindsdb" },
  { slug: "mint-lang", name: "Mint Lang" },
  { slug: "mio", name: "Mio" },
  { slug: "miro", name: "Miro" },
  { slug: "mist", name: "Mist" },
  { slug: "mistral-ai", name: "Mistral Ai" },
  { slug: "mithril", name: "Mithril" },
  { slug: "mixmax", name: "Mixmax" },
  { slug: "mixpanel", name: "Mixpanel" },
  { slug: "mlab", name: "Mlab" },
  { slug: "mobx", name: "Mobx" },
  { slug: "mocha", name: "Mocha" },
  { slug: "mockflow", name: "Mockflow" },
  { slug: "modernizr", name: "Modernizr" },
  { slug: "modx", name: "Modx" },
  { slug: "momentjs", name: "Momentjs" },
  { slug: "monday", name: "Monday" },
  { slug: "monero", name: "Monero" },
  { slug: "mongodb", name: "MongoDB" },
  { slug: "mono", name: "Mono" },
  { slug: "moon", name: "Moon" },
  { slug: "mootools", name: "Mootools" },
  { slug: "morpheus", name: "Morpheus" },
  { slug: "mozilla", name: "Mozilla" },
  { slug: "mparticle", name: "Mparticle" },
  { slug: "mps", name: "Mps" },
  { slug: "msw", name: "Msw" },
  { slug: "multipass", name: "Multipass" },
  { slug: "mysql", name: "MySQL" },
  { slug: "naiveui", name: "Naiveui" },
  { slug: "namecheap", name: "Namecheap" },
  { slug: "nanonets", name: "Nanonets" },
  { slug: "nasm", name: "Nasm" },
  { slug: "nativescript", name: "Nativescript" },
  { slug: "nats", name: "Nats" },
  { slug: "neat", name: "Neat" },
  { slug: "neo4j", name: "Neo4j" },
  { slug: "neon", name: "Neon" },
  { slug: "neovim", name: "Neovim" },
  { slug: "nestjs", name: "Nestjs" },
  { slug: "netbeans", name: "Netbeans" },
  { slug: "netflix", name: "Netflix" },
  { slug: "netlify", name: "Netlify" },
  { slug: "neverinstall", name: "Neverinstall" },
  { slug: "new-relic", name: "New Relic" },
  { slug: "nextjs", name: "Next.js" },
  { slug: "nginx", name: "Nginx" },
  { slug: "ngrok", name: "Ngrok" },
  { slug: "nhost", name: "Nhost" },
  { slug: "nightwatch", name: "Nightwatch" },
  { slug: "nim-lang", name: "Nim Lang" },
  { slug: "nocodb", name: "Nocodb" },
  { slug: "nodal", name: "Nodal" },
  { slug: "node-sass", name: "Node Sass" },
  { slug: "nodebots", name: "Nodebots" },
  { slug: "nodejs", name: "Node.js" },
  { slug: "nodejs-icon-alt", name: "Nodejs Icon Alt" },
  { slug: "nodemon", name: "Nodemon" },
  { slug: "nodeos", name: "Nodeos" },
  { slug: "nodewebkit", name: "Nodewebkit" },
  { slug: "nomad", name: "Nomad" },
  { slug: "notion", name: "Notion" },
  { slug: "noysi", name: "Noysi" },
  { slug: "npm", name: "npm" },
  { slug: "nuclide", name: "Nuclide" },
  { slug: "numpy", name: "Numpy" },
  { slug: "nuxt", name: "Nuxt" },
  { slug: "nvidia", name: "Nvidia" },
  { slug: "nvm", name: "Nvm" },
  { slug: "nx", name: "Nx" },
  { slug: "oauth", name: "Oauth" },
  { slug: "observablehq", name: "Observablehq" },
  { slug: "obsidian", name: "Obsidian" },
  { slug: "ocaml", name: "Ocaml" },
  { slug: "octodns", name: "Octodns" },
  { slug: "octopus-deploy", name: "Octopus Deploy" },
  { slug: "okta", name: "Okta" },
  { slug: "olark", name: "Olark" },
  { slug: "onesignal", name: "Onesignal" },
  { slug: "open-graph", name: "Open Graph" },
  { slug: "open-zeppelin", name: "Open Zeppelin" },
  { slug: "openai", name: "OpenAI" },
  { slug: "openapi", name: "Openapi" },
  { slug: "opencart", name: "Opencart" },
  { slug: "opencollective", name: "Opencollective" },
  { slug: "opencv", name: "Opencv" },
  { slug: "openframeworks", name: "Openframeworks" },
  { slug: "opengl", name: "Opengl" },
  { slug: "openjs-foundation", name: "Openjs Foundation" },
  { slug: "openlayers", name: "Openlayers" },
  { slug: "opensearch", name: "Opensearch" },
  { slug: "openshift", name: "Openshift" },
  { slug: "opensource", name: "Opensource" },
  { slug: "openstack", name: "Openstack" },
  { slug: "opentelemetry", name: "Opentelemetry" },
  { slug: "opera", name: "Opera" },
  { slug: "opsgenie", name: "Opsgenie" },
  { slug: "optimizely", name: "Optimizely" },
  { slug: "oracle", name: "Oracle" },
  { slug: "oreilly", name: "Oreilly" },
  { slug: "origami", name: "Origami" },
  { slug: "origin", name: "Origin" },
  { slug: "oshw", name: "Oshw" },
  { slug: "osquery", name: "Osquery" },
  { slug: "overloop", name: "Overloop" },
  { slug: "p5js", name: "P5js" },
  { slug: "packer", name: "Packer" },
  { slug: "pagekit", name: "Pagekit" },
  { slug: "pagekite", name: "Pagekite" },
  { slug: "pagerduty", name: "Pagerduty" },
  { slug: "panda", name: "Panda" },
  { slug: "pandacss", name: "Pandacss" },
  { slug: "pandas", name: "Pandas" },
  { slug: "parcel", name: "Parcel" },
  { slug: "parse", name: "Parse" },
  { slug: "parsehub", name: "Parsehub" },
  { slug: "partytown", name: "Partytown" },
  { slug: "passbolt", name: "Passbolt" },
  { slug: "passport", name: "Passport" },
  { slug: "patreon", name: "Patreon" },
  { slug: "payload", name: "Payload" },
  { slug: "paypal", name: "Paypal" },
  { slug: "peer5", name: "Peer5" },
  { slug: "pepperoni", name: "Pepperoni" },
  { slug: "percona", name: "Percona" },
  { slug: "percy", name: "Percy" },
  { slug: "perf-rocks", name: "Perf Rocks" },
  { slug: "perl", name: "Perl" },
  { slug: "perplexity", name: "Perplexity" },
  { slug: "phalcon", name: "Phalcon" },
  { slug: "phoenix", name: "Phoenix" },
  { slug: "php", name: "PHP" },
  { slug: "php-alt", name: "Php Alt" },
  { slug: "phpstorm", name: "Phpstorm" },
  { slug: "pinecone", name: "Pinecone" },
  { slug: "pinia", name: "Pinia" },
  { slug: "pinterest", name: "Pinterest" },
  { slug: "pipedream", name: "Pipedream" },
  { slug: "pipedrive", name: "Pipedrive" },
  { slug: "pipefy", name: "Pipefy" },
  { slug: "pivotal_tracker", name: "Pivotal_tracker" },
  { slug: "pixijs", name: "Pixijs" },
  { slug: "pkg", name: "Pkg" },
  { slug: "planetscale", name: "Planetscale" },
  { slug: "planless", name: "Planless" },
  { slug: "plasmic", name: "Plasmic" },
  { slug: "plastic-scm", name: "Plastic Scm" },
  { slug: "platformio", name: "Platformio" },
  { slug: "play", name: "Play" },
  { slug: "playwright", name: "Playwright" },
  { slug: "pluralsight", name: "Pluralsight" },
  { slug: "pm2", name: "Pm2" },
  { slug: "pnpm", name: "Pnpm" },
  { slug: "pocket-base", name: "Pocket Base" },
  { slug: "poeditor", name: "Poeditor" },
  { slug: "polymer", name: "Polymer" },
  { slug: "postcss", name: "Postcss" },
  { slug: "postgraphile", name: "Postgraphile" },
  { slug: "postgresql", name: "PostgreSQL" },
  { slug: "posthog", name: "Posthog" },
  { slug: "postman", name: "Postman" },
  { slug: "pouchdb", name: "Pouchdb" },
  { slug: "preact", name: "Preact" },
  { slug: "precursor", name: "Precursor" },
  { slug: "prerender", name: "Prerender" },
  { slug: "prestashop", name: "Prestashop" },
  { slug: "presto", name: "Presto" },
  { slug: "prettier", name: "Prettier" },
  { slug: "prisma", name: "Prisma" },
  { slug: "prismic", name: "Prismic" },
  { slug: "processing", name: "Processing" },
  { slug: "processwire", name: "Processwire" },
  { slug: "productboard", name: "Productboard" },
  { slug: "producthunt", name: "Producthunt" },
  { slug: "progress", name: "Progress" },
  { slug: "prometheus", name: "Prometheus" },
  { slug: "promises", name: "Promises" },
  { slug: "proofy", name: "Proofy" },
  { slug: "protoio", name: "Protoio" },
  { slug: "protonet", name: "Protonet" },
  { slug: "protractor", name: "Protractor" },
  { slug: "prott", name: "Prott" },
  { slug: "pug", name: "Pug" },
  { slug: "pulumi", name: "Pulumi" },
  { slug: "pumpkindb", name: "Pumpkindb" },
  { slug: "puppet", name: "Puppet" },
  { slug: "puppeteer", name: "Puppeteer" },
  { slug: "purescript", name: "Purescript" },
  { slug: "pushbullet", name: "Pushbullet" },
  { slug: "pusher", name: "Pusher" },
  { slug: "pwa", name: "Pwa" },
  { slug: "pycharm", name: "Pycharm" },
  { slug: "pypi", name: "Pypi" },
  { slug: "pyscript", name: "Pyscript" },
  { slug: "python", name: "Python" },
  { slug: "pytorch", name: "PyTorch" },
  { slug: "pyup", name: "Pyup" },
  { slug: "q", name: "Q" },
  { slug: "qdrant", name: "Qdrant" },
  { slug: "qlik", name: "Qlik" },
  { slug: "qt", name: "Qt" },
  { slug: "qualcomm", name: "Qualcomm" },
  { slug: "quarkus", name: "Quarkus" },
  { slug: "quay", name: "Quay" },
  { slug: "quobyte", name: "Quobyte" },
  { slug: "quora", name: "Quora" },
  { slug: "qwik", name: "Qwik" },
  { slug: "r-lang", name: "R Lang" },
  { slug: "rabbitmq", name: "Rabbitmq" },
  { slug: "rackspace", name: "Rackspace" },
  { slug: "rails", name: "Rails" },
  { slug: "ramda", name: "Ramda" },
  { slug: "raml", name: "Raml" },
  { slug: "rancher", name: "Rancher" },
  { slug: "raphael", name: "Raphael" },
  { slug: "raspberry-pi", name: "Raspberry Pi" },
  { slug: "rax", name: "Rax" },
  { slug: "react", name: "React" },
  { slug: "react-query", name: "React Query" },
  { slug: "react-router", name: "React Router" },
  { slug: "react-spring", name: "React Spring" },
  { slug: "react-styleguidist", name: "React Styleguidist" },
  { slug: "reactivex", name: "Reactivex" },
  { slug: "realm", name: "Realm" },
  { slug: "reapp", name: "Reapp" },
  { slug: "reasonml", name: "Reasonml" },
  { slug: "recaptcha", name: "Recaptcha" },
  { slug: "recoil", name: "Recoil" },
  { slug: "reddit", name: "Reddit" },
  { slug: "redhat", name: "Redhat" },
  { slug: "redis", name: "Redis" },
  { slug: "redsmin", name: "Redsmin" },
  { slug: "redux", name: "Redux" },
  { slug: "redux-observable", name: "Redux Observable" },
  { slug: "redux-saga", name: "Redux Saga" },
  { slug: "redwoodjs", name: "Redwoodjs" },
  { slug: "reindex", name: "Reindex" },
  { slug: "relay", name: "Relay" },
  { slug: "release", name: "Release" },
  { slug: "remix", name: "Remix" },
  { slug: "renovatebot", name: "Renovatebot" },
  { slug: "replay", name: "Replay" },
  { slug: "replit", name: "Replit" },
  { slug: "require", name: "Require" },
  { slug: "rescript", name: "Rescript" },
  { slug: "rest-li", name: "Rest Li" },
  { slug: "rethinkdb", name: "Rethinkdb" },
  { slug: "retool", name: "Retool" },
  { slug: "riak", name: "Riak" },
  { slug: "rider", name: "Rider" },
  { slug: "riot", name: "Riot" },
  { slug: "risingwave", name: "Risingwave" },
  { slug: "rocket-chat", name: "Rocket Chat" },
  { slug: "rocksdb", name: "Rocksdb" },
  { slug: "rocky-linux", name: "Rocky Linux" },
  { slug: "rollbar", name: "Rollbar" },
  { slug: "rollupjs", name: "Rollupjs" },
  { slug: "rome", name: "Rome" },
  { slug: "ros", name: "Ros" },
  { slug: "rsa", name: "Rsa" },
  { slug: "rsmq", name: "Rsmq" },
  { slug: "rubocop", name: "Rubocop" },
  { slug: "ruby", name: "Ruby" },
  { slug: "rubygems", name: "Rubygems" },
  { slug: "rubymine", name: "Rubymine" },
  { slug: "rum", name: "Rum" },
  { slug: "runscope", name: "Runscope" },
  { slug: "rush", name: "Rush" },
  { slug: "rust", name: "Rust" },
  { slug: "rxdb", name: "Rxdb" },
  { slug: "safari", name: "Safari" },
  { slug: "sagui", name: "Sagui" },
  { slug: "sails", name: "Sails" },
  { slug: "salesforce", name: "Salesforce" },
  { slug: "sameroom", name: "Sameroom" },
  { slug: "samsung", name: "Samsung" },
  { slug: "sanity", name: "Sanity" },
  { slug: "sap", name: "SAP" },
  { slug: "sass", name: "Sass" },
  { slug: "sass-doc", name: "Sass Doc" },
  { slug: "saucelabs", name: "Saucelabs" },
  { slug: "scala", name: "Scala" },
  { slug: "scaledrone", name: "Scaledrone" },
  { slug: "scribd", name: "Scribd" },
  { slug: "seaborn", name: "Seaborn" },
  { slug: "section", name: "Section" },
  { slug: "segment", name: "Segment" },
  { slug: "selenium", name: "Selenium" },
  { slug: "semantic-release", name: "Semantic Release" },
  { slug: "semantic-ui", name: "Semantic Ui" },
  { slug: "semantic-web", name: "Semantic Web" },
  { slug: "semaphoreci", name: "Semaphoreci" },
  { slug: "sencha", name: "Sencha" },
  { slug: "sendgrid", name: "Sendgrid" },
  { slug: "seneca", name: "Seneca" },
  { slug: "sensu", name: "Sensu" },
  { slug: "sentry", name: "Sentry" },
  { slug: "sequelize", name: "Sequelize" },
  { slug: "serverless", name: "Serverless" },
  { slug: "sherlock", name: "Sherlock" },
  { slug: "shields", name: "Shields" },
  { slug: "shipit", name: "Shipit" },
  { slug: "shogun", name: "Shogun" },
  { slug: "shopify", name: "Shopify" },
  { slug: "shortcut", name: "Shortcut" },
  { slug: "sidekiq", name: "Sidekiq" },
  { slug: "signal", name: "Signal" },
  { slug: "sigstore", name: "Sigstore" },
  { slug: "sinatra", name: "Sinatra" },
  { slug: "singlestore", name: "Singlestore" },
  { slug: "sitepoint", name: "Sitepoint" },
  { slug: "sk-hynix", name: "Sk Hynix" },
  { slug: "skaffolder", name: "Skaffolder" },
  { slug: "sketch", name: "Sketch" },
  { slug: "skylight", name: "Skylight" },
  { slug: "skype", name: "Skype" },
  { slug: "slack", name: "Slack" },
  { slug: "slides", name: "Slides" },
  { slug: "slidev", name: "Slidev" },
  { slug: "slim", name: "Slim" },
  { slug: "smartling", name: "Smartling" },
  { slug: "smashingmagazine", name: "Smashingmagazine" },
  { slug: "snap-svg", name: "Snap Svg" },
  { slug: "snaplet", name: "Snaplet" },
  { slug: "snowflake", name: "Snowflake" },
  { slug: "snowpack", name: "Snowpack" },
  { slug: "snyk", name: "Snyk" },
  { slug: "socket.io", name: "Socket.io" },
  { slug: "solarwinds", name: "Solarwinds" },
  { slug: "solid", name: "Solid" },
  { slug: "solidity", name: "Solidity" },
  { slug: "solidjs", name: "Solidjs" },
  { slug: "solr", name: "Solr" },
  { slug: "sonarcloud", name: "Sonarcloud" },
  { slug: "sonarlint", name: "Sonarlint" },
  { slug: "sonarqube", name: "Sonarqube" },
  { slug: "soundcloud", name: "Soundcloud" },
  { slug: "sourcegraph", name: "Sourcegraph" },
  { slug: "sourcetree", name: "Sourcetree" },
  { slug: "spark", name: "Spark" },
  { slug: "sparkpost", name: "Sparkpost" },
  { slug: "speakerdeck", name: "Speakerdeck" },
  { slug: "speedcurve", name: "Speedcurve" },
  { slug: "spidermonkey", name: "Spidermonkey" },
  { slug: "spinnaker", name: "Spinnaker" },
  { slug: "splunk", name: "Splunk" },
  { slug: "spotify", name: "Spotify" },
  { slug: "spree", name: "Spree" },
  { slug: "spring", name: "Spring" },
  { slug: "sqlite", name: "Sqlite" },
  { slug: "square", name: "Square" },
  { slug: "squarespace", name: "Squarespace" },
  { slug: "sst", name: "Sst" },
  { slug: "stability-ai", name: "Stability Ai" },
  { slug: "stackbit", name: "Stackbit" },
  { slug: "stackblitz", name: "Stackblitz" },
  { slug: "stackoverflow", name: "Stack Overflow" },
  { slug: "stackshare", name: "Stackshare" },
  { slug: "stately", name: "Stately" },
  { slug: "statuspage", name: "Statuspage" },
  { slug: "stdlib", name: "Stdlib" },
  { slug: "steam", name: "Steam" },
  { slug: "stenciljs", name: "Stenciljs" },
  { slug: "stetho", name: "Stetho" },
  { slug: "stickermule", name: "Stickermule" },
  { slug: "stigg", name: "Stigg" },
  { slug: "stimulus", name: "Stimulus" },
  { slug: "stitch", name: "Stitch" },
  { slug: "stoplight", name: "Stoplight" },
  { slug: "storyblocks", name: "Storyblocks" },
  { slug: "storyblok", name: "Storyblok" },
  { slug: "storybook", name: "Storybook" },
  { slug: "strapi", name: "Strapi" },
  { slug: "streamlit", name: "Streamlit" },
  { slug: "strider", name: "Strider" },
  { slug: "stripe", name: "Stripe" },
  { slug: "struts", name: "Struts" },
  { slug: "styleci", name: "Styleci" },
  { slug: "stylefmt", name: "Stylefmt" },
  { slug: "stylelint", name: "Stylelint" },
  { slug: "stylis", name: "Stylis" },
  { slug: "stylus", name: "Stylus" },
  { slug: "stytch", name: "Stytch" },
  { slug: "sublimetext", name: "Sublimetext" },
  { slug: "subversion", name: "Subversion" },
  { slug: "sugarss", name: "Sugarss" },
  { slug: "supabase", name: "Supabase" },
  { slug: "supertokens", name: "Supertokens" },
  { slug: "surge", name: "Surge" },
  { slug: "surrealdb", name: "Surrealdb" },
  { slug: "survicate", name: "Survicate" },
  { slug: "suse", name: "Suse" },
  { slug: "susy", name: "Susy" },
  { slug: "svelte", name: "Svelte" },
  { slug: "svelte-kit", name: "Svelte Kit" },
  { slug: "svg", name: "Svg" },
  { slug: "svgator", name: "Svgator" },
  { slug: "swagger", name: "Swagger" },
  { slug: "swc", name: "Swc" },
  { slug: "swift", name: "Swift" },
  { slug: "swiftype", name: "Swiftype" },
  { slug: "swimm", name: "Swimm" },
  { slug: "swr", name: "Swr" },
  { slug: "symfony", name: "Symfony" },
  { slug: "sysdig", name: "Sysdig" },
  { slug: "t3", name: "T3" },
  { slug: "tableau", name: "Tableau" },
  { slug: "taiga", name: "Taiga" },
  { slug: "tailwindcss", name: "Tailwindcss" },
  { slug: "tapcart", name: "Tapcart" },
  { slug: "taskade", name: "Taskade" },
  { slug: "tastejs", name: "Tastejs" },
  { slug: "tauri", name: "Tauri" },
  { slug: "tealium", name: "Tealium" },
  { slug: "teamcity", name: "Teamcity" },
  { slug: "teamgrid", name: "Teamgrid" },
  { slug: "teamwork", name: "Teamwork" },
  { slug: "telegram", name: "Telegram" },
  { slug: "tensorflow", name: "TensorFlow" },
  { slug: "terminal", name: "Terminal" },
  { slug: "terraform", name: "Terraform" },
  { slug: "terser", name: "Terser" },
  { slug: "testcafe", name: "Testcafe" },
  { slug: "testing-library", name: "Testing Library" },
  { slug: "testlodge", name: "Testlodge" },
  { slug: "threejs", name: "Threejs" },
  { slug: "thymeleaf", name: "Thymeleaf" },
  { slug: "tidal", name: "Tidal" },
  { slug: "tiktok", name: "Tiktok" },
  { slug: "tnw", name: "Tnw" },
  { slug: "todoist", name: "Todoist" },
  { slug: "todomvc", name: "Todomvc" },
  { slug: "tomcat", name: "Tomcat" },
  { slug: "toml", name: "Toml" },
  { slug: "tor", name: "Tor" },
  { slug: "tor-browser", name: "Tor Browser" },
  { slug: "traackr", name: "Traackr" },
  { slug: "trac", name: "Trac" },
  { slug: "travis-ci", name: "Travis Ci" },
  { slug: "travis-ci-monochrome", name: "Travis Ci Monochrome" },
  { slug: "treasuredata", name: "Treasuredata" },
  { slug: "treehouse", name: "Treehouse" },
  { slug: "trello", name: "Trello" },
  { slug: "trpc", name: "Trpc" },
  { slug: "truffle", name: "Truffle" },
  { slug: "tsmc", name: "Tsmc" },
  { slug: "tsnode", name: "Tsnode" },
  { slug: "tsuru", name: "Tsuru" },
  { slug: "tumblr", name: "Tumblr" },
  { slug: "tunein", name: "Tunein" },
  { slug: "tuple", name: "Tuple" },
  { slug: "turbopack", name: "Turbopack" },
  { slug: "turborepo", name: "Turborepo" },
  { slug: "turret", name: "Turret" },
  { slug: "twilio", name: "Twilio" },
  { slug: "twitch", name: "Twitch" },
  { slug: "twitter", name: "Twitter" },
  { slug: "typeform", name: "Typeform" },
  { slug: "typeorm", name: "Typeorm" },
  { slug: "typescript", name: "TypeScript" },
  { slug: "typescript-icon-round", name: "Typescript Icon Round" },
  { slug: "typesense", name: "Typesense" },
  { slug: "typo3", name: "Typo3" },
  { slug: "ubuntu", name: "Ubuntu" },
  { slug: "udacity", name: "Udacity" },
  { slug: "udemy", name: "Udemy" },
  { slug: "uikit", name: "Uikit" },
  { slug: "umu", name: "Umu" },
  { slug: "unbounce", name: "Unbounce" },
  { slug: "undertow", name: "Undertow" },
  { slug: "unionpay", name: "Unionpay" },
  { slug: "unitjs", name: "Unitjs" },
  { slug: "unito", name: "Unito" },
  { slug: "unity", name: "Unity" },
  { slug: "unjs", name: "Unjs" },
  { slug: "unocss", name: "Unocss" },
  { slug: "unrealengine", name: "Unrealengine" },
  { slug: "upcase", name: "Upcase" },
  { slug: "upstash", name: "Upstash" },
  { slug: "upwork", name: "Upwork" },
  { slug: "user-testing", name: "User Testing" },
  { slug: "uservoice", name: "Uservoice" },
  { slug: "uwsgi", name: "Uwsgi" },
  { slug: "v8", name: "V8" },
  { slug: "v8-ignition", name: "V8 Ignition" },
  { slug: "v8-turbofan", name: "V8 Turbofan" },
  { slug: "vaadin", name: "Vaadin" },
  { slug: "vaddy", name: "Vaddy" },
  { slug: "vagrant", name: "Vagrant" },
  { slug: "vault", name: "Vault" },
  { slug: "vector", name: "Vector" },
  { slug: "vercel", name: "Vercel" },
  { slug: "verdaccio", name: "Verdaccio" },
  { slug: "vernemq", name: "Vernemq" },
  { slug: "vim", name: "Vim" },
  { slug: "vimeo", name: "Vimeo" },
  { slug: "visa", name: "Visa" },
  { slug: "visaelectron", name: "Visaelectron" },
  { slug: "visual-studio", name: "Visual Studio" },
  { slug: "visual-studio-code", name: "Visual Studio Code" },
  { slug: "vitejs", name: "Vitejs" },
  { slug: "vitess", name: "Vitess" },
  { slug: "vitest", name: "Vitest" },
  { slug: "vivaldi", name: "Vivaldi" },
  { slug: "vlang", name: "Vlang" },
  { slug: "vmware", name: "Vmware" },
  { slug: "void", name: "Void" },
  { slug: "volar", name: "Volar" },
  { slug: "vue", name: "Vue" },
  { slug: "vuetifyjs", name: "Vuetifyjs" },
  { slug: "vueuse", name: "Vueuse" },
  { slug: "vulkan", name: "Vulkan" },
  { slug: "vultr", name: "Vultr" },
  { slug: "vwo", name: "Vwo" },
  { slug: "w3c", name: "W3c" },
  { slug: "waffle", name: "Waffle" },
  { slug: "wagtail", name: "Wagtail" },
  { slug: "wakatime", name: "Wakatime" },
  { slug: "walkme", name: "Walkme" },
  { slug: "watchman", name: "Watchman" },
  { slug: "waypoint", name: "Waypoint" },
  { slug: "wayscript", name: "Wayscript" },
  { slug: "wearos", name: "Wearos" },
  { slug: "weave", name: "Weave" },
  { slug: "web.dev", name: "Web.dev" },
  { slug: "web3js", name: "Web3js" },
  { slug: "webassembly", name: "Webassembly" },
  { slug: "webcomponents", name: "Webcomponents" },
  { slug: "webdriverio", name: "Webdriverio" },
  { slug: "webflow", name: "Webflow" },
  { slug: "webgpu", name: "Webgpu" },
  { slug: "webhint", name: "Webhint" },
  { slug: "webhooks", name: "Webhooks" },
  { slug: "webix", name: "Webix" },
  { slug: "webkit", name: "Webkit" },
  { slug: "webmin", name: "Webmin" },
  { slug: "webpack", name: "Webpack" },
  { slug: "webplatform", name: "Webplatform" },
  { slug: "webrtc", name: "Webrtc" },
  { slug: "websocket", name: "Websocket" },
  { slug: "webstorm", name: "Webstorm" },
  { slug: "webtorrent", name: "Webtorrent" },
  { slug: "weebly", name: "Weebly" },
  { slug: "whalar", name: "Whalar" },
  { slug: "whatsapp", name: "Whatsapp" },
  { slug: "whatwg", name: "Whatwg" },
  { slug: "wicket", name: "Wicket" },
  { slug: "wifi", name: "Wifi" },
  { slug: "wildfly", name: "Wildfly" },
  { slug: "windi-css", name: "Windi Css" },
  { slug: "winglang", name: "Winglang" },
  { slug: "wire", name: "Wire" },
  { slug: "wix", name: "Wix" },
  { slug: "wmr", name: "Wmr" },
  { slug: "woocommerce", name: "Woocommerce" },
  { slug: "woopra", name: "Woopra" },
  { slug: "wordpress", name: "Wordpress" },
  { slug: "wordpress-icon-alt", name: "Wordpress Icon Alt" },
  { slug: "workboard", name: "Workboard" },
  { slug: "workos", name: "Workos" },
  { slug: "workplace", name: "Workplace" },
  { slug: "wpengine", name: "Wpengine" },
  { slug: "wufoo", name: "Wufoo" },
  { slug: "x", name: "X" },
  { slug: "xamarin", name: "Xamarin" },
  { slug: "xampp", name: "Xampp" },
  { slug: "xata", name: "Xata" },
  { slug: "xcart", name: "Xcart" },
  { slug: "xcode", name: "Xcode" },
  { slug: "xero", name: "Xero" },
  { slug: "xray-for-jira", name: "Xray For Jira" },
  { slug: "xstate", name: "Xstate" },
  { slug: "xtend", name: "Xtend" },
  { slug: "xwiki", name: "Xwiki" },
  { slug: "yahoo", name: "Yahoo" },
  { slug: "yaml", name: "Yaml" },
  { slug: "yammer", name: "Yammer" },
  { slug: "yandex-ru", name: "Yandex Ru" },
  { slug: "yarn", name: "Yarn" },
  { slug: "ycombinator", name: "Ycombinator" },
  { slug: "yeoman", name: "Yeoman" },
  { slug: "yii", name: "Yii" },
  { slug: "youtrack", name: "Youtrack" },
  { slug: "youtube", name: "YouTube" },
  { slug: "yugabyte", name: "Yugabyte" },
  { slug: "zabbix", name: "Zabbix" },
  { slug: "zapier", name: "Zapier" },
  { slug: "zend-framework", name: "Zend Framework" },
  { slug: "zendesk", name: "Zendesk" },
  { slug: "zenhub", name: "Zenhub" },
  { slug: "zeplin", name: "Zeplin" },
  { slug: "zeroheight", name: "Zeroheight" },
  { slug: "zig", name: "Zig" },
  { slug: "zod", name: "Zod" },
  { slug: "zoho", name: "Zoho" },
  { slug: "zoom", name: "Zoom" },
  { slug: "zorin-os", name: "Zorin Os" },
  { slug: "zsh", name: "Zsh" },
  { slug: "zube", name: "Zube" },
  { slug: "zulip", name: "Zulip" },
  { slug: "zwave", name: "Zwave" },
];

export function logoPath(slug: string): string {
  return "/logos/" + slug + ".svg";
}
